server:
    port: 8011

user:
    userServiceUrl: http://192.168.11.142:8010/
#management:
#  endpoint:
#    health:
#      show-details: always
#    info:
#      enabled: false
#  server:
#    port: 8012

