server:
    port: 8011
user:
    userServiceUrl: http://localhost:8010/
eureka:
  client:
    healthcheck:
      enabled: false
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka/
spring:
  application:
    name: microservice-simple-consumer-movie

