version: '2'
services:
    eureka:
        build:
          context: ./microservice-discovery-eureka
          dockerfile: Dockerfile
          args:
            JAR_FILE: ./microservice-discovery-eureka/target/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar
#        image: hjwjw/microservice-discovery-eureka:latest
        ports:
          - "8761:8761"
#    config:
#        image: hjwjw/microservice-config-server:latest
#        ports:
#          - "8082:8082"
    microservice-simple-provider-user:
        build:
          context: ./microservice-simple-provider-user
          dockerfile: Dockerfile
          args:
            JAR_FILE: ./microservice-simple-provider-user/target/microservice-simple-provider-user-0.0.1-SNAPSHOT.jar
#        image: hjwjw/microservice-simple-provider-user:latest
        ports:
          - "8010:8010"
    microservice-simple-consumer-movie:
        build:
          context: ./microservice-simple-consumer-movie
          dockerfile: Dockerfile
          args:
            JAR_FILE: ./microservice-simple-consumer-movie/target/microservice-simple-provider-user-0.0.1-SNAPSHOT.jar
#        image: hjwjw/microservice-simple-consumer-movie:latest
        ports:
          - "8011:8011"
        depends_on:
          - microservice-simple-provider-user