version: '2'
services:
    eureka:
#        build:
#          context: ./
#          dockerfile: Dockerfile
#          args:
#            JAR_FILE: target/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar
        image: hjwjw/microservice-discovery-eureka:latest
        ports:
          - "8761:8761"
        depends_on:
          - config
    config:
        image: hjwjw/microservice-config-server:latest
        ports:
          - "8082:8082"
    microservice-provider-user:
        image: hjwjw/microservice-provider-user:latest
        ports:
          - "8005:8005"
        depends_on:
          - config
          - eureka
    microservice-consumer-movie:
        image: hjwjw/microservice-consumer-movie:latest
        ports:
          - "8010:8010"
        depends_on:
          - config
          - eureka
          - provider