version: '2'
services:
    eureka:
#        build:
#          context: ./
#          dockerfile: Dockerfile
#          args:
#            JAR_FILE: target/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar
        image: hjwjw/microservice-discovery-eureka:latest
        ports:
          - "8761:8761"
#    config:
#        image: hjwjw/microservice-config-server:latest
#        ports:
#          - "8082:8082"
    microservice-simple-provider-user:
        image: hjwjw/microservice-simple-provider-user:latest
        ports:
          - "8010:8010"
    microservice-simple-consumer-movie:
        image: hjwjw/microservice-simple-consumer-movie:latest
        ports:
          - "8011:8011"
        depends_on:
          - microservice-simple-provider-user