spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka
zuul:
#  prefix: /getProfile
#  strip-prefix: false
  routes:
    user:
      path: /user/**
      serviceId: microservice-provider-user
#  ignored-patterns: /**/getProfile/**
#  ignored-services: microservice-config-server
#    microservice-provider-user: /user/**
logging:
  level:
    com.netflix: debug
#ribbon:
#  eureka:
#    enabled: false
