version: '2'
services:
    eureka:
#        build:
#          context: ./
#          dockerfile: Dockerfile
#          args:
#            JAR_FILE: target/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar
        image: hjwjw/microservice-discovery-eureka:latest
        ports:
          - "8761:8761"