version: '2'
services:
    eureka:
        build:
          context: ./
          dockerfile: Dockerfile
          args:
            JAR_FILE: target/microservice-discovery-eureka-0.0.1-SNAPSHOT.jar
        ports:
          - "8761:8761"