server:
    port: 8011
user:
    userServiceUrl: http://localhost:8000/
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: false
  server:
    port: 8012

logging:                           #配置日志级别，让Hibernate 打印执行的SQL
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
spring:
  application:
    name: microservice-simple-consumer-movie-trace-zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

