server:
  port: 8010

spring:
  application:
      name: microservice-simple-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl_auto: none
  h2:
    console:
      path: /h2-console               #h2 web控制台路径
      enabled: true                   #开启 Web Console
      settings:
        web-allow-others: true        #允许远程访问 Web Console
  datasource:
    platform: h2                      #指定数据源类型
    url: jdbc:h2:tcp://192.168.11.142:9200/~/test   # 指定url
    schema: classpath:schema.sql      #指定数据库的数据脚本
    data: classpath:data.sql          #指定数据库的数据脚本
eureka:
  client:
    healthcheck:
      enabled: false
    service-url:
      defaultZone: http://user:admin@192.168.11.142:8761/eureka/

logging:                           #配置日志级别，让Hibernate 打印执行的SQL
  level:
    org.springframework: info
    org.hibernate: info
## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@


