spring:
  application:
    name: microservice-trace-zipkin-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: 123456
zipkin:
  storage:
    type: mysql

server:
  port: 9411