server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-movie2
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

