
security:
  basic:
    enabled: true                     #开启HTTP basic的认证
  user:
    name: user                        #配置登录账号证
    password: admin                   #配置登录密码
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://user:admin@peer1:8761/eureka/,http://user:admin@peer3:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
