spring:
  application:
    name: microservice-discovery-eureka
security:
  basic:
    enabled: true                     #开启HTTP basic的认证
  user:
    name: user                        #配置登录账号证
    password: admin                   #配置登录密码
---
spring:
  profiles: peer1                     # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1                   # 指定当profile=peer1时，主机名是peer1
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://user:admin@peer2:8762/eureka/,http://user:admin@peer3:8763/eureka/      # 将自己注册到peer2和peer3这两个Eureka上面去
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://user:admin@peer1:8761/eureka/,http://user:admin@peer3:8763/eureka/
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://user:admin@peer1:8761/eureka/,http://user:admin@peer2:8762/eureka/
    register-with-eureka: true
    fetch-registry: true


