
security:
  basic:
    enabled: true                     #开启HTTP basic的认证
  user:
    name: user                        #配置登录账号证
    password: admin                   #配置登录密码
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:admin@localhost:8761/eureka/
