server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
        defaultZone: http://user:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#使用rabbitmq收集监控数去掉
#turbine:
#  app-config: microservice-consumer-movie,microservice-consumer-movie2
#  cluster-name-expression: "'default'"